### ISSUE TITLE
Does the module support repeating forms?

### ISSUE THREAD

**Issue by pbchase** [ctsit/auto_populate_fields#18]
Hugo writes

> From: Hugo Potier <hugo.potier@xxx.xxx>
> Subject: Auto Populate Fields - v2.2
> Date: April 11, 2019 at 4:18:26 AM EDT
> To: pbc@xxx.xxx
> Cc: tls@xxx.xxx, suryayalla@xxx.xxx, planka@xxx.xxx, rajputd@xxx.xxx, swehmeyer@xxx.xxx, tbembersimeao@xxx.xxx, mconlon@ufl.> edu
> 
> Dear Philip,
> 
> I'm using your very good "Auto Populate Fields - v2.2" module, and I'm wondering if there's not an issue on it with > multiple repeating event.
> 
> Here a working solution:
> 
> ![2019-04-11 09_52_10-Test module prepopulate _ REDCap](https://user-images.githubusercontent.com/3356493/56371048-5d699780-61ca-11e9-9833-4d0309ed3ee2.png)
> ![2019-04-11 09_52_26-Test module prepopulate _ REDCap](https://user-images.githubusercontent.com/3356493/56371054-635f7880-61ca-11e9-968d-2f11109312c0.png)
> 
> 
> Here a none working solution (the data are not copied from previous repeating event):
> ![image](https://user-images.githubusercontent.com/3356493/56371067-6a868680-61ca-11e9-9c62-cd1b8b7dde8a.png)
> 
> To reproduce the error :
> Add data to "Baseline Data" in Enrollment
> Go to Dose 1 all data from previous event are well copied (and click save button)
> and Go to Visit 1 (same form) the data from previous event are not copied.
> 
> Perhaps, I do something wrong.
> 
> I look forward to hearing from you,
> 
> Hugo
> 
> PS: Please find in attachment the "Baseline Data" form
> 
[BaselineData_2019-04-11_1012.zip](https://github.com/ctsit/auto_populate_fields/files/3095033/BaselineData_2019-04-11_1012.zip)

**Comment by hpotier** [comment]
Hi,

Do you have any update about this issue?

Thanks a lot,

Hugo

**Comment by pbchase** [comment]
@ChemiKyle, could you review this to see if support we can add support for repeating events without breaking the module?

**Comment by marlycormar** [comment]
Issue fixed by PR #24.

**Comment by mschulze0** [comment]
Hi,
I have a very similar setup to the non-working setup of OP (except that I have some repeating instruments in the first event) and @DEFAULT-FROM-PREVIOUS-EVENT is not working for me when I use it in a repeating event.

**Comment by mschulze0** [comment]
Hi,

as a test I just copied the project and disabled all repeating instruments in my first event so that I now have the same structure as OP. Still doesn't work.

**Comment by pbchase** [comment]
@mschulze0, could you open a new issue at https://github.com/ctsit/auto_populate_fields/issues and describe your experiences there? It's much easier for us to keep things straight this way. 

Thanks, 
Philip
